/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardImg: typeof import('bootstrap-vue-next')['BCardImg']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    IMdiArrowLeftBold: typeof import('~icons/mdi/arrow-left-bold')['default']
    IMdiArrowRightBold: typeof import('~icons/mdi/arrow-right-bold')['default']
    IMdiBack: typeof import('~icons/mdi/back')['default']
    IMdiForward: typeof import('~icons/mdi/forward')['default']
    IMdiNext: typeof import('~icons/mdi/next')['default']
    IMdiRefresh: typeof import('~icons/mdi/refresh')['default']
    IMdiSpeak: typeof import('~icons/mdi/speak')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
