FROM node:16 AS frontendbuild
WORKDIR /app

COPY ./src/frontend .

RUN npm install
RUN npm run build

# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY ./src/backend/requirements.txt .

# Install the project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files into the container
COPY ./src/backend/ .
COPY --from=frontendbuild /app/dist ./wwwroot

# Set any necessary environment variables
ENV PYTHONUNBUFFERED=1

# Expose any necessary ports (e.g., for a web server)
EXPOSE 8000

# Specify the command to run when the container starts
CMD ["python", "app.py"]