name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: paulhacktarchivators.azurecr.io
  IMAGE_NAME: paulhacktarchivators

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINERREGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINERREGISTRY_KEY }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          file: ./src/Dockerfile
